# Generated by Django 5.0.6 on 2024-06-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to='')),
                ('descrizione', models.CharField(max_length=20)),
                ('dato', models.FloatField()),
            ],
        ),
    ]
